#changeLogFile: changelog/db.changelog-master.xml

url: jdbc:postgresql://work-done-uat.c1quccouuse0.ap-south-1.rds.amazonaws.com:5432/work_done_uat
username: postgres
password: $ecPass12345%$#
driver: org.postgresql.Driver
logLevel: info
defaultSchemaName: public