changeLogFile: changelog/db.changelog-master.xml
url: jdbc:postgresql://ep-crimson-mud-a1ec79qp-pooler.ap-southeast-1.aws.neon.tech/work-done-test?sslmode=require
username: work-done-test_owner
#password: npg_LDOSE7QmkU4Y
driver: org.postgresql.Driver
logLevel: info
defaultSchemaName: core_schema